# Universal estimator

Let $f(x|d_1,...,d_n)$ be a function, that for any fixed values of the parameters $d_i$, reduces to a PDF of x; $f$ thus is a family of functions, e.g., *log normal*.

$estimator(f, sample)$ is a function which learns the parameters $d_i$ of $f$ from a single input *sample* ($m$ observations drawn using $f$).

## Method
> 1. Generate synthetic *samples*.
> 2. Learn a DNN model from the synthetic data.
> 3. Predict the parameters $d_i$ on the input *sample*.

## Parameter range adjustment
The *estimator* is allowed to assume that the range of the parameter values is $(-\frac{1}{2}, \frac{1}{2})$.

For that we use *Range Adjustment*:
> Input:
> 1. A funation $f(x|d_i)$ as defined above
> 2. Bounds on the parameters $d_i$

> Output:
> - A function $g(x|t_i)$, which is the same as $f$, except that $t_i$ are in the range $(-\frac{1}{2}, \frac{1}{2})$, 
> and such that $t_i$ are “typically” around 0.

> Let: $h(d)$ be a mapping function from $range(d)$ to the range $(-\frac{1}{2}, \frac{1}{2})$, where $h$ is continuous within $range(d)$.
>
> $h^{-1}(t)$ is therefore a mapping function from the range $(-\frac{1}{2}, \frac{1}{2})$ to $range(d)$.
>
> Let: $g(x|t_i) = f(x|h^{-1}(t_i))$ where $h^{-1}(t_i)$ is a inverse of the *mapping* $h(d)$ of the bounds on the parameters $d_i$.

We use the *range adjustment* as follows:
> 1. Generate synthetic *samples* using $f(x|h^{-1}(t_i))$ where $t_i$ are drawn from $(-\frac{1}{2}, \frac{1}{2})$.
> 2. Learn a DNN model from the synthetic data.
> 3. Predict the parameters $d_i$ on the input *sample*.


### Range adjustment using $logit(x)$
The standard *logistic* function is defined as: $𝜎(x) = 1 / (1 + e^{-x})$ for $x ∈ (-∞, ∞)$.

<p style="text-align:center;"><img src="images/logistic.png" alt="logistic(x)" title="logistic(x), x ∈ (−∞,∞)" /></p>

The *logit* is the inverse of the *logistic* function.

The *logit* function is defined as: $logit(x) = 𝜎^{-1}(x) = ln( x / (1-x) )$ for $x ∈ (0,1)$.

<p style="text-align:center;"><img src="images/logit.png" alt="logit" title="logit(x), x ∈ (0,1)" /></p>

We can use the *logistic* function and its *logit* inverse as follows:
> Let: $h(d) = logit(d)$ for $d ∈ (0,1)$
>
> Than $h^{-1}(t) = 𝜎(t)$ for $t ∈ (-∞, ∞)$

> We define a function to return another function, i.e., an adjuster of a parameter from the range $(0, 1)$ 
>
> to the original range $(low, high)$ that a function takes.


In [1]:
import math
# from scipy.special import expit, logit

def expit(x):
    # expit(x) = 1 / (1 + e^(-x))
    # defined in (-INF, INF)
    return 1 / (1 + math.exp(-x))

def logit(p):
    # logit(p) = inv(expit) = ln(p/(1-p))
    # defined in (0, 1)
    if 0 == p: return -math.inf
    if 1 == p: return math.inf
    return math.log(p/(1-p))

def adjuster_logit(low, high):
    # adjuster is defined in (-INF, INF)
    # low: parameter lower bound
    # high: parameter higher bound
    # return: a function defined in (0,1) that maps it's parameter (x) to the original range (low,high).

    LOW = 0 if -math.inf == low else expit(low)
    HIGH = 1 if math.inf == high else expit(high)

    def adjust(x):
        # adjust is defined in (0, 1)
        if x < 0: return -math.inf
        if x > 1: return math.inf
        return logit(LOW + x * (HIGH - LOW))
    
    return adjust


### Range adjustment using $arctan(x)$
> <img src="images/tan.png" />
> <img src="images/arctan.png" />


In [2]:
def adjuster_arctan(low, high):
    # adjuster is defined in (-INF, INF)
    # low: parameter lower bound
    # high: parameter higher bound
    # return: a function defined in (0,1) that maps it's parameter (x) to the original range (low,high).

    LOW = -math.pi/2 if -math.inf == low else math.atan(low)
    HIGH = math.pi/2 if math.inf == high else math.atan(high)

    def adjust(x):
        # adjust is defined in (0, 1)
        if x < 0: return -math.inf
        if x > 1: return math.inf
        return math.tan(LOW + x * (HIGH - LOW))
    
    return adjust

### Test adjusters

In [3]:
print(f"adjuster_logit(2,10)(0): {adjuster_logit(low=-2, high=10)(0)}")
print(f"adjuster_logit(2,10)(1): {adjuster_logit(low=-2, high=10)(1)}")
print(f"adjuster_arctan(2,10)(0): {adjuster_arctan(low=-2, high=10)(0)}")
print(f"adjuster_arctan(2,10)(1): {adjuster_arctan(low=-2, high=10)(1)}")


adjuster_logit(2,10)(0): -2.0
adjuster_logit(2,10)(1): 10.00000000000097
adjuster_arctan(2,10)(0): -1.9999999999999996
adjuster_arctan(2,10)(1): 10.00000000000001


In [4]:
# adjust = adjuster_logit(low=0, high=10.0)
# adjust( np.random.uniform(0.0, 1.0, size=1)[0])

# Universal estimator

-  Apply 2D  range adjustment; for now, it will be independent parameters: should adjust to $(-\frac{1}{2}, \frac{1}{2})^2, (n=2)$.  
   In this case: we want the range to be an n-dimensional unit cube; this makes it easier to understand subranges: e.g., 0.1-0.2.  
   We also introduce some "prior" in a very convoluted way. A priori, the range is -∞ to +∞ and we know nothing about where the parameter is. After range adjustment, we shrink some regions by a large factor and others by a small factor. So, we favor the center of the range. We may even beat Cramer-Rao for this reason.

-  Select 5 or so longtail distributions (we may need to change the families later). Do range adjustment, and it should be sensible in the sense that it is approximately centered.

- Do range adjustment (orthogonal for now, i.e, independently for each original parameter).

- Draw a mesh on the unit square, say with a resolution of 0.1, this gives 81 points for each mesh. Maybe 1/11 resolution? Maybe include the last and first row and column. 

- For each point in the mesh, run learning experiment producing:
   - Several (say 10-100) learning experiments. without focusing for now.
   - Compute the average error of the 10-100 experiments. MSE rules
   - Compute the Cramer Rao bound (numerically if the analytical solution is not possible)
   - Divide the MSE by Cramer Rao.
  
- Draw the 3D manifold on the mesh.

### Expected results:

1. Hopefully, we are at most 2 times worse than CR. 
2. Hopefully, the CR is never singular, i.e. not zero nor infinity.


In [5]:
import math
import numpy as np

def generate_data(N, M, sample, param_ranges, nbins=-1):
    """
    param_ranges: [dX2] array of parameter ranges (e.g. for 2 parmeters: [[0, 10], [0, math.inf]])
    """
    
    # output (generate samples)
    samples = np.zeros((N, M), dtype=float)
    
    # generate N parameter cubes in the range (-0.5, +0.5)
    params = np.zeros((N, 2), dtype=float)

    param_adjusters = [adjuster_logit(low=pr[0], high=pr[1]) for pr in param_ranges]
    
    n_params = param_ranges.shape[0]
    
    for i in range(N):
        for param_i in range(n_params):
            adjuster = param_adjusters[param_i]
            # ti is in (-0.5, 0.5)
            ti = np.random.uniform(0.0, 1.0, size=1)[0]
            # di is in (di_low, di_high)
            params[i, param_i] = adjuster(ti)
    
    # repeat N times: draw a sample from distribution (M observations)
    for i in range(N):
        samples[i, :] = sample(params[i], size=M)
    
    # create a histogram from each sample
    if nbins < 0:
        nbins = int(np.max(samples))+1
    
    histogram_matrix = np.apply_along_axis(
       lambda a: np.histogram(a, bins=nbins, range=(0, nbins), density=False)[0], 1, samples)

    return samples, params, histogram_matrix

In [6]:
from scipy import stats
from scipy.stats import lognorm

def lognormal_sample(params, size):
    return lognorm.rvs(s=params[0], loc=params[1], size=size)

sample = lognormal_sample
ranges = np.array(
    [[0.0, 1.0], 
     [0.0, math.inf]]
)

samples, params, histogram_matrix = generate_data(
    N=8, M=256, sample=sample, param_ranges=ranges)

# print(samples)
# print(params)
print(histogram_matrix)


[[ 55 119  48  18   8   4   2   1   0   0   1   0   0   0   0]
 [  0 256   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  58 118  52  12   7   1   3   3   1   1   0   0   0   0]
 [ 69 149  32   6   0   0   0   0   0   0   0   0   0   0   0]
 [  0 229  27   0   0   0   0   0   0   0   0   0   0   0   0]
 [112  97  30  12   4   0   0   0   0   0   0   0   0   0   1]
 [  0   1 144  92  15   3   1   0   0   0   0   0   0   0   0]
 [  0 256   0   0   0   0   0   0   0   0   0   0   0   0   0]]


In [7]:
from scipy import stats
from scipy.stats import yulesimon

def yulesimon_sample(params, size):
    return yulesimon.rvs(alpha=params[0], loc=params[1], size=size)

sample = yulesimon_sample
ranges = np.array(
    [[2.0, 3.0], 
     [0.0, math.inf]]
)

samples, params, histogram_matrix = generate_data(
    N=8, M=256, sample=sample, param_ranges=ranges)

# print(samples)
# print(params)
print(histogram_matrix)


[[  0 184  41 ...   0   0   0]
 [  0   0 183 ...   0   0   0]
 [  0   0 155 ...   0   0   1]
 ...
 [  0   0 181 ...   0   0   0]
 [  0 161  58 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [8]:
# import dnn library
%run dnn.ipynb
