In [11]:
import numpy as np
from skimage.measure import block_reduce

In [3]:
# a = np.arange(20).reshape(5,4)

# print(a)

# for i in [2,3]:
#     for j in range(0, a.shape[1]-i+1, i):
#         print(np.append(a, a[j:j+i,:], axis=1))

# print()
# print(a)

In [71]:
# t = np.array([[4,5,0,7,1,6,8,3,2,9],[4,5,0,7,1,6,8,3,2,9]])
t = np.array([4,5,0,7,1,6,8,3,2,9])

In [72]:
block_reduce(t, block_size=(2,), func=np.sum)

array([ 9,  7,  7, 11, 11])

In [73]:
block_reduce(t, block_size=(3,), func=np.sum)

array([ 9, 14, 13,  9])

In [74]:
np.add.reduceat(t, np.arange(0, len(t), 2))

array([ 9,  7,  7, 11, 11])

In [75]:
np.add.reduceat(t, np.arange(0, len(t), 3))

array([ 9, 14, 13,  9])

In [31]:
t2 = np.array([[4,5,0,7,1,6,8,3,2,9],[4,5,0,7,1,6,8,3,2,9]])

In [76]:
t2

array([[4, 5, 0, 7, 1, 6, 8, 3, 2, 9],
       [4, 5, 0, 7, 1, 6, 8, 3, 2, 9]])

In [78]:
np.add.reduceat(t2, np.arange(0, t2.shape[1], 2), axis=1)

array([[ 9,  7,  7, 11, 11],
       [ 9,  7,  7, 11, 11]])

In [63]:
t3 = np.array([[4,5,0,7,1,6,8,3,2,9],[4,5,0,7,1,6,8,3,2,9],[4,5,0,7,1,6,8,3,2,9]])

In [64]:
np.add.reduceat(t3, np.arange(0, len(t), 2), axis=1)

array([[ 9,  7,  7, 11, 11],
       [ 9,  7,  7, 11, 11],
       [ 9,  7,  7, 11, 11]])

In [50]:
def B(k):
    """
    k = [1 .. M + DELTA]
    B(k) = 
    """
    pass

In [52]:
a = np.array([[4,5,0,7,1,6,8,3,2,9],[4,5,0,7,1,6,8,3,2,9],[4,5,0,7,1,6,8,3,2,9]])

In [82]:
a
a2 = np.add.reduceat(a, np.arange(0, a.shape[1], 2), axis=1)
a3 = np.add.reduceat(a, np.arange(0, a.shape[1], 3), axis=1)

In [83]:
a

array([[4, 5, 0, 7, 1, 6, 8, 3, 2, 9],
       [4, 5, 0, 7, 1, 6, 8, 3, 2, 9],
       [4, 5, 0, 7, 1, 6, 8, 3, 2, 9]])

In [84]:
a2

array([[ 9,  7,  7, 11, 11],
       [ 9,  7,  7, 11, 11],
       [ 9,  7,  7, 11, 11]])

In [85]:
a3

array([[ 9, 14, 13,  9],
       [ 9, 14, 13,  9],
       [ 9, 14, 13,  9]])

In [93]:
OUT = a.copy()

In [94]:
OUT = np.hstack((OUT,a2))
OUT

array([[ 4,  5,  0,  7,  1,  6,  8,  3,  2,  9,  9,  7,  7, 11, 11],
       [ 4,  5,  0,  7,  1,  6,  8,  3,  2,  9,  9,  7,  7, 11, 11],
       [ 4,  5,  0,  7,  1,  6,  8,  3,  2,  9,  9,  7,  7, 11, 11]])

In [95]:
OUT = np.hstack((OUT,a3))
OUT

array([[ 4,  5,  0,  7,  1,  6,  8,  3,  2,  9,  9,  7,  7, 11, 11,  9,
        14, 13,  9],
       [ 4,  5,  0,  7,  1,  6,  8,  3,  2,  9,  9,  7,  7, 11, 11,  9,
        14, 13,  9],
       [ 4,  5,  0,  7,  1,  6,  8,  3,  2,  9,  9,  7,  7, 11, 11,  9,
        14, 13,  9]])

In [12]:
def foo():
    return {'a_N':2, 'a_sqrt_mse':4, 'a_avg_abs_errors':6}

zzz = foo()
zzz

{'a_N': 2, 'a_sqrt_mse': 4, 'a_avg_abs_errors': 6}

In [14]:
users = []
for i in range(3):
    users.append(('username_{}'.format(i), 'user{}'.format(i)))
    users.append(('age_{}'.format(i), i))
dict(users)

{'username_0': 'user0',
 'age_0': 0,
 'username_1': 'user1',
 'age_1': 1,
 'username_2': 'user2',
 'age_2': 2}

In [49]:
import numpy as np

def max_every_n_elements(a, n):
    mod = a.shape[0] % n
    if mod > 0:
        a = np.hstack((a, np.zeros_like(a, shape=[a.shape[0],mod])))
    b = np.reshape(a, (-1,int(a.shape[1]/n),n))
    c = np.max(b, axis=2)
    return c

n = 3
a = np.array([[1,2,3,1,2,3,1,2,3,1,2,3,0], [1,2,3,1,2,3,1,2,3,1,2,3,0]])
c = max_every_n_elements(a, n)
c
# mod = 2
# np.hstack((a, np.zeros_like(a, shape=[a.shape[0],mod])))

array([[3, 3, 3, 3, 0],
       [3, 3, 3, 3, 0]])